#!/usr/bin/env python3
"""
🧪 INTEGRATION DEMO SCRIPT
=========================

This script demonstrates the complete integration between ETL automation 
and review mining engine with real examples.

Usage:
    python demo_integration.py
"""

import logging
import sys
from pathlib import Path
import json
import pandas as pd
from datetime import datetime

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

def demo_integrated_pipeline():
    """Demonstrate the complete integrated pipeline"""
    
    print("\n" + "="*80)
    print(" ETL AUTOMATION + REVIEW MINING INTEGRATION DEMO")
    print("="*80)
    
    try:
        from integrated_etl_pipeline import IntegratedETLMiningPipeline
        
        # Initialize pipeline
        pipeline = IntegratedETLMiningPipeline()
        
        # Demo configuration with popular products
        demo_products = [
            {
                'product_id': 'B0CX59H5W7',  # Echo Dot 
                'page_limit': 1,             # Just 1 page for demo
                'headless': True             # Run headlessly
            }
        ]
        
        print(f"\n DEMO CONFIGURATION:")
        print(f"   Products to analyze: {[p['product_id'] for p in demo_products]}")
        print(f"   Pages per product: {demo_products[0]['page_limit']}")
        print(f"   Headless mode: {demo_products[0]['headless']}")
        print(f"   Review mining: ENABLED")
        
        print(f"\n Starting integrated pipeline demonstration...")
        
        # Execute pipeline
        success = pipeline.execute_full_pipeline(
            products_config=demo_products,
            enable_mining=True,
            enable_debug=False
        )
        
        if success:
            print("\n DEMO COMPLETED SUCCESSFULLY!")
            
            # Show generated files
            show_generated_files()
            
            # Show insights preview
            show_insights_preview()
            
        else:
            print("\n DEMO FAILED!")
            print("Check logs for details.")
        
    except ImportError as e:
        print(f"\n Import Error: {e}")
        print("Make sure all dependencies are installed:")
        print("pip install -r requirements.txt")
        print("playwright install chromium")
        
    except Exception as e:
        print(f"\n Demo failed with error: {e}")
        logger.error(f"Demo execution failed: {e}")

def show_generated_files():
    """Show the files generated by the pipeline"""
    print(f"\n GENERATED FILES:")
    
    directories_to_check = {
        'data/reviews': 'Raw extracted reviews',
        'data/processed': 'Enhanced reviews with NLP features', 
        'data/insights': 'Comprehensive insights reports',
        'data/logs': 'Pipeline execution logs'
    }
    
    for directory, description in directories_to_check.items():
        dir_path = Path(directory)
        if dir_path.exists():
            files = list(dir_path.iterdir())
            if files:
                latest_file = max(files, key=lambda f: f.stat().st_mtime)
                size_mb = latest_file.stat().st_size / (1024*1024)
                print(f"    {description}")
                print(f"      Latest: {latest_file.name} ({size_mb:.2f} MB)")
            else:
                print(f"    {description}: No files")
        else:
            print(f"    {description}: Directory not found")

def show_insights_preview():
    """Show a preview of the generated insights"""
    print(f"\n INSIGHTS PREVIEW:")
    
    insights_dir = Path('data/insights')
    if insights_dir.exists():
        json_files = list(insights_dir.glob('*.json'))
        if json_files:
            latest_insights = max(json_files, key=lambda f: f.stat().st_mtime)
            
            try:
                with open(latest_insights, 'r', encoding='utf-8') as f:
                    insights = json.load(f)
                
                # Extract key metrics
                overall = insights.get('overall_statistics', {})
                sentiment = insights.get('sentiment_analysis', {})
                emotions = insights.get('emotion_analysis', {})
                aspects = insights.get('product_aspects', {})
                
                print(f"\n    OVERALL STATISTICS:")
                print(f"      Total Reviews Analyzed: {overall.get('total_reviews', 'N/A')}")
                print(f"      Average Rating: {overall.get('average_rating', 'N/A')}")
                print(f"      Average Sentiment: {overall.get('average_sentiment', 'N/A')}")
                print(f"      Quality Score: {overall.get('average_quality_score', 'N/A')}")
                
                print(f"\n    SENTIMENT BREAKDOWN:")
                print(f"      Positive: {sentiment.get('positive_reviews_pct', 'N/A')}%")
                print(f"      Negative: {sentiment.get('negative_reviews_pct', 'N/A')}%")
                print(f"      Neutral: {sentiment.get('neutral_reviews_pct', 'N/A')}%")
                
                if emotions:
                    print(f"\n    TOP EMOTIONS:")
                    for emotion, data in list(emotions.items())[:3]:
                        if isinstance(data, dict) and 'total_mentions' in data:
                            print(f"      {emotion.capitalize()}: {data['total_mentions']} mentions")
                
                if aspects:
                    print(f"\n    PRODUCT ASPECTS:")
                    for aspect, data in list(aspects.items())[:3]:
                        if isinstance(data, dict) and 'mentions' in data:
                            sentiment_score = data.get('avg_sentiment', 0)
                            print(f"      {aspect.capitalize()}: {data['mentions']} mentions (sentiment: {sentiment_score:.2f})")
                
            except Exception as e:
                print(f"    Error reading insights: {e}")
        else:
            print("    No insights files found")
    else:
        print("    Insights directory not found")

def demo_api_endpoints():
    """Demonstrate API endpoints"""
    print(f"\n🔌 API INTEGRATION DEMO:")
    print(f"   To test the API endpoints:")
    print(f"   1. Run: python api_controller.py")
    print(f"   2. Open: http://127.0.0.1:8000/docs")
    print(f"   3. Test endpoints:")
    print(f"      - GET  /api/status")
    print(f"      - POST /api/etl/run")
    print(f"      - GET  /api/data/latest")
    print(f"      - GET  /api/insights/latest")

def demo_manual_execution():
    """Show manual execution commands"""
    print(f"\n MANUAL EXECUTION EXAMPLES:")
    print(f"   # Single product with mining:")
    print(f"   python integrated_etl_pipeline.py --asins B0CX59H5W7 --pages 1 --headless --mining")
    print(f"   ")
    print(f"   # Multiple products:")
    print(f"   python integrated_etl_pipeline.py --asins B0CX59H5W7,B0FHB5V36G --pages 2 --headless --mining")
    print(f"   ")
    print(f"   # Debug mode:")
    print(f"   python integrated_etl_pipeline.py --asins B0CX59H5W7 --pages 1 --debug --mining")

if __name__ == "__main__":
    print(" Choose demonstration option:")
    print("1. Full integrated pipeline demo (recommended)")
    print("2. Show API integration info")
    print("3. Show manual execution examples")
    print("4. All of the above")
    
    try:
        choice = input("\nEnter choice (1-4): ").strip()
        
        if choice == "1":
            demo_integrated_pipeline()
        elif choice == "2":
            demo_api_endpoints()
        elif choice == "3":
            demo_manual_execution()
        elif choice == "4":
            demo_integrated_pipeline()
            demo_api_endpoints() 
            demo_manual_execution()
        else:
            print("Invalid choice. Running full demo...")
            demo_integrated_pipeline()
            
    except KeyboardInterrupt:
        print("\n\n Demo interrupted. Goodbye!")
    except Exception as e:
        print(f"\n Demo error: {e}")
        logger.error(f"Demo error: {e}")